name: test-conda-env-py3
channels:
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy

# to avoid conflict with system openmpi's libhwloc
- libhwloc=1
- pocl

- islpy
- pyopencl
- python=3
- gmsh

- pip
- pip:
    - git+https://github.com/inducer/pytools
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy
    - git+https://github.com/inducer/meshmode
    - git+https://github.com/inducer/dagrt
    - git+https://github.com/inducer/leap
    - git+https://github.com/inducer/pyvisfile
    - mpi4py
    - pymetis
