name: test-conda-env-py3
channels:
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy
- pocl
- islpy
- pyopencl
- python=3
- gmsh

- pip
- pip:
    - git+https://github.com/inducer/pytools
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy
    - git+https://github.com/inducer/meshmode
